version : "3.7"
networks:
  internal:
    driver: bridge


services:
  stoptranscode:
      image: stoptranscode
      build: ./
      container_name: stoptranscode
      restart: always
      hostname: stoptranscode
      volumes:
        - ./:/data
      environment:
        - TAUTULLI_PORT=
        - TAUTULLI_IP=
        - TAUTULLI_API=
      networks:
      - internal